version: "3.7"
services:
  invest_crm_api:
    build: .
    container_name: invest_crm_api
    command: bash -c "uvicorn src.main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8000:80
    depends_on:
      - db

  db:
    container_name: db-pg
    hostname: db-pg
    image: postgres:16.1-alpine3.18
    volumes:
      - invest_crm_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432

volumes:
  invest_crm_postgres_data:
